---
language: python
python: "2.7"

env:
  - distribution: debian
    version: stretch
  - distribution: debian
    version: buster

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt

install:
  # Install Ansible.
  - pip install ansible==2.7.13

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
